### ISSUE TITLE
Missing Asset

### ISSUE THREAD

**Issue by xwy-bit** [StanfordVL/behavior#12]
I run the demo code 
```
import omnigibson as og 
from omnigibson.macros import gm 
import cv2
import yaml 
import utils.sim_utils as su

# Start with an empty configuration
gm.USE_GPU_DYNAMICS = True
cfg = dict()
cfg = yaml.load(open('config/base_config.yaml', "r"), Loader=yaml.FullLoader)

# Load the environment
try:
    env = og.Environment(configs=cfg, action_timestep=1/60., physics_timestep=1/60.)
except Exception as e:
    og.log.error(e)
```
with config 
```
env:
  initial_pos_z_offset: 0.1

render:
  viewer_width: 1280
  viewer_height: 720

scene:
  type: InteractiveTraversableScene
  scene_model:  Beechwood_0_int # example scene model
  trav_map_resolution: 0.1
  trav_map_erosion: 2
  trav_map_with_objects: true
  build_graph: true
  num_waypoints: 1
  waypoint_resolution: 0.2
  not_load_object_categories: []
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: OG
  include_robots: true

robots:
  - type: Fetch
    obs_modalities: [scan, rgb, depth]
    scale: 1.0
    self_collision: false
    action_normalize: true
    action_type: continuous
    grasping_mode: physical
    rigid_trunk: false
    default_trunk_offset: 0.365
    default_arm_pose: diagonal30
    reset_joint_pos: tuck
    visible_only: True
    visible: False
    controller_config:
      base:
        name: DifferentialDriveController
      arm_0:
        name: InverseKinematicsController
        kv: 2.0
      gripper_0:
        name: MultiFingerGripperController
        mode: binary
      camera:
        name: JointController
        use_delta_commands: False

objects: []

task:
  type: BehaviorTask
  activity_name:  make_a_salad # example task
  activity_definition_id: 0
  activity_instance_id: 0
  predefined_problem: null
  online_object_sampling: false
  debug_object_sampling: null
  highlight_task_relevant_objects: false
  termination_config:
    max_steps: 500
  reward_config:
    r_potential: 1.0
```
But it output the error 
```
[INFO] [omnigibson.objects.object_base] Loaded chickpea_template at /World/chickpea/template
2024-03-09 14:42:21 [26,242ms] [Error] [omni.hydra] Asset path "materials/chickpea-jwqrer-base_link-albedo.png" not found

2024-03-09 14:42:21 [26,242ms] [Error] [omni.hydra] Asset path "materials/chickpea-jwqrer-base_link-metalness.png" not found

2024-03-09 14:42:21 [26,243ms] [Error] [omni.hydra] Asset path "materials/chickpea-jwqrer-base_link-normal.png" not found

2024-03-09 14:42:21 [26,243ms] [Error] [omni.hydra] Asset path "materials/chickpea-jwqrer-base_link-roughness.png" not found

```
can anyone tell me where to find these assets?
